version: '3.8'

services:
  my-db:
    image: mysql:8.0
    env_file:
      - config/.env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  my-app:
    image: kaynecherem/tempconverter:dev
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - config/.env
    depends_on:
      - my-db

volumes:
  db-data:
